name: Self Hosted Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - run: echo "Hello from Self Hosted Runner"

      - run: hostname

      - run: whoami

      - run: pwd

      - run: kubectl get nodes
      - name: Show GitHub Variables
         run: |
          echo "Repository : $GITHUB_REPOSITORY"
          echo "Commit SHA : $GITHUB_SHA"
          echo "Branch     : $GITHUB_REF_NAME"
          echo "Workspace  : $GITHUB_WORKSPACE"
          echo "Runner     : $RUNNER_NAME"
